site_name: 'Binary Ninja User Documentation'
site_url: 'https://docs.binary.ninja/'
repo_url: 'https://binary.ninja/'
repo_name: 'binary.ninja'
site_description: 'Documentation for the Binary Ninja reverse engineering platform'
site_author: 'Vector 35 Inc'
use_directory_urls: false
extra_css: ['docs.css', 'github.min.css', 'juxtapose.min.css']
extra_javascript: ['highlight.min.js', 'cpp.min.js', 'python.min.js', 'juxtapose.min.js']
theme:
    name: material
    custom_dir: overrides
    favicon: 'img/favicon.ico'
    font: false
    highlightjs: false
    palette:
        scheme: binja
        accent: red
    features:
        - navigation.tracking
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.prune
        - navigation.indexes
        - navigation.top
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 191   # ? / /

        copyright: '(<a href="https://creativecommons.org/licenses/by/3.0/">cc</a>) <a href="https://vector35.com/">Vector 35 Inc</a>'

plugins:
    - search
    - offline

markdown_extensions:
    - codehilite
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: True

nav:
    - Home: 'index.md'
    - Getting Started: 'getting-started.md'
        #
        #- User Manual: 'guide/'
        #- Developer Guide: 'dev/'
        #- About: 'about/'
    - User Manual:
        - 'guide/index.md'
        - Plugins: 'guide/plugins.md'
        - Settings: 'guide/settings.md'
        - Types: 'guide/type.md'
        - C++ Types: 'guide/cpp.md'
        - Debugger: 'guide/debugger.md'
        - Objective-C (Beta): 'guide/objectivec.md'
        - Troubleshooting: 'guide/troubleshooting.md'
    - Developer Guide:
        - 'dev/index.md'
        - Important Concepts: 'dev/concepts.md'
        - Cookbook: 'dev/cookbook.md'
        - Writing Plugins: 'dev/plugins.md'
        - Automation: 'dev/batch.md'
        - BNIL Guide&#58; Overview: 'dev/bnil-overview.md'
        - BNIL Guide&#58; LLIL: 'dev/bnil-llil.md'
        - BNIL Guide&#58; MLIL: 'dev/bnil-mlil.md'
        - Flag Guide: 'dev/flags.md'
        - Workflows: 'dev/workflows.md'
        - Creating Themes: 'dev/themes.md'
        - Contributing Documentation: 'dev/documentation.md'
    - About:
        - 'about/index.md'
        - License: 'about/license.md'
        - Open Source: 'about/open-source.md'

extra:
    disablesearch: True
    logo: 'images/logo.png'
